### ISSUE TITLE
document GPU feature

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/info_grid#152]
- #153 
- #154 
- #155 
- #156 
- #157

**Comment by Mik-TF** [comment]
gpu content is available in the branch: development-gpu, https://github.com/threefoldtech/info_grid/tree/development_gpu
We will merge this to dev and master when GPU is available on main net.

**Comment by mohamedamer453** [comment]
For [go-client](https://github.com/threefoldtech/info_grid/blob/development_gpu/src/go/grid3_go_vm_with_gpu.md), [terraform](https://github.com/threefoldtech/info_grid/blob/development_gpu/src/terraform/terraform_gpu_support.md), and [typescript client](https://github.com/threefoldtech/info_grid/blob/development_gpu/src/javascript/grid3_javascript_gpu_support.md) everything looks good on the [development-gpu branch](https://github.com/threefoldtech/info_grid/tree/development_gpu).

However in the tfchain section there's still a mention of `has_gpu` in the [GPU Support](https://github.com/threefoldtech/info_grid/blob/development_gpu/src/tfchain/tfchain.md#gpu-support) section and it was dropped in https://github.com/threefoldtech/tfchain/issues/759

For the UI:
   - [Playground](https://github.com/threefoldtech/info_grid/blob/development/src/playground/fullVm.md#full-virtual-machine) mentions the gpu flag in the fullvm docs.
   - [Statistics](https://github.com/threefoldtech/info_grid/blob/development_gpu/src/dashboard/explorer/explorer_gpu_support.md#statistics-view)
   - [Dashboard](https://github.com/threefoldtech/info_grid/blob/development_gpu/src/dashboard/explorer/explorer_gpu_support.md#tf-explorer) the screenshot for the explorer should be updated since the position of the `GPU` toggle was changed.
