### ISSUE TITLE
Video in docs still shows the planetary network in left menu.

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/info_grid#306]
https://manual.grid.tf/getstarted/TF_Connect/TF_Connect.html

![image](https://github.com/threefoldtech/threefold_connect/assets/16083592/4e78c605-6161-41d7-a166-59eb4f2d2def)

Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

**Comment by Mik-TF** [comment]
@ramezsaeed @xmonader 
Do we simply remove the video or we create another one?

**Comment by Mik-TF** [comment]
@ramezsaeed @xmonader 

We can remove the video and the picture with the planetary network being shown, but I think we could just let it all there, since the video does not focus on this aspect. It's outdated but not in the way of the video explanation.

If we want to remove it, I can do a quick PR with:

* remove the planetary reference
    * remove the embedded video
    * crop the image showing the planetary network

Let me know if we keep as is and just don't mind the planetary network reference, or if we want to remove as explained above.

**Comment by ramezsaeed** [comment]
@Mik-TF 
For me I recommend to remove it yes, so we avoid any miss leading to planetary network tab which is not available anymore in the current release.
lets see @xmonader opinion here too.

**Comment by Mik-TF** [comment]
Good! Once, we get a confirmation from Thabet, I will remove what needs to be removed and make a PR.

**Comment by Mik-TF** [comment]
* Fix when #346 is merged.
