### ISSUE TITLE
review terraform docs

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/info_grid#5]
review for terraform docs is needed
make sure everything is up to date

**Comment by mohamedamer453** [comment]
Everything looks good except for a couple of remarks.

### Tutorial

- In the tutorial section a couple of commands still have `-parallelism=1`

   ![image](https://user-images.githubusercontent.com/101194226/227130399-d28b8eb0-4e8e-4129-90dd-59ffbce3c4b6.png)

- In the [`How to use a Terraform File`](https://www2.manual.grid.tf/terraform/terraform_get_started.html#how-to-use-a-terraform-file) Section it's mentioned that you can provide a specific version but in the `terraform's global section` it only shows the `source` variable and it doesn't mention the `version` variable.

   ![image](https://user-images.githubusercontent.com/101194226/227131013-63f88ce8-f947-4cb1-9949-2427b3b16b46.png)
   
   ![image](https://user-images.githubusercontent.com/101194226/227131179-cbf6ac45-e6a3-4642-83e9-e57df0933d19.png)

- In the [`Which flists to use`](https://www2.manual.grid.tf/terraform/terraform_get_started.html#which-flists-to-use-in-vm) section. the provided url doesn't work.

   ![image](https://user-images.githubusercontent.com/101194226/227131813-3e868121-0c92-407b-983f-07a9d321bb3c.png)

### Delete

- In the delete section, the part where it mentions deleting the contracts from the weblets should be updated since it shows a very old screenshot of the contracts list, and the note that mentions that it's not easy to see what to delete should be removed since currently deployments from terraform include metadata which makes it easy to identify what these contracts are used for, also the `Show Details` button which displays the full details of each contract.

   ![image](https://user-images.githubusercontent.com/101194226/227133391-1b9d1c56-b6da-409f-9d85-037babf73acb.png)

### Virtual Machine

- Section titles Needs to be capitalized.

   ![image](https://user-images.githubusercontent.com/101194226/227134395-97c1f61e-c8f8-43d3-8bcc-fc161b4e116a.png)

   ![image](https://user-images.githubusercontent.com/101194226/227134438-9299e19b-579c-435b-aa8d-f94b7f711e9f.png)

   ![image](https://user-images.githubusercontent.com/101194226/227134517-44fdf7d8-a3c1-4105-ac51-ea7d91718b7c.png)

- A small typo in the network section.

   ![image](https://user-images.githubusercontent.com/101194226/227134740-dfebb4ec-b246-49ca-a1d7-be99e5e31f2e.png)

- In the [`Remark multiple VMs`](https://www2.manual.grid.tf/terraform/resources/terraform_vm.html#remark-multiple-vms) section, both links provided in the `flist` option are not working. first one redirects to `threefold:zos_fs` and the second redirects to `https://www2.manual.grid.tf/terraform/resources/grid3_supported_flists`

   ![image](https://user-images.githubusercontent.com/101194226/227135477-86dbb3d2-4936-439e-9fe1-bc6502cc6680.png)

### Web Gateway

- Section titles Needs to be capitalized.

   ![image](https://user-images.githubusercontent.com/101194226/227136557-9e875ada-2cbb-4d1a-be04-5806a294f234.png)

   ![image](https://user-images.githubusercontent.com/101194226/227136624-eb06738b-a29c-4300-93f2-a7627ebedd5b.png)

**Comment by ashraffouda** [comment]
all comments are done except for ` which flists to use`, the link is already working 
https://manual.grid.tf/terraform/resources/terraform_vm.html#which-flists-to-use

**Comment by mohamedamer453** [comment]
> all comments are done except for ` which flists to use`, the link is already working https://manual.grid.tf/terraform/resources/terraform_vm.html#which-flists-to-use

All of the mentioned remarks were fixed except for the link in https://www2.manual.grid.tf/terraform/terraform_get_started.html#which-flists-to-use-in-vm it's still broken and redirects to `https://www2.manual.grid.tf/terraform/manual3_iac/grid3_supported_flists.html`

[Screencast from 23-03-23 13:53:31.webm](https://user-images.githubusercontent.com/101194226/227195867-59747991-af6b-42e7-84d1-f6449a59dfcb.webm)

**Comment by ashraffouda** [comment]
yeah, found it
I saw another link for lists that works :), anyways it is fixed now

**Comment by mohamedamer453** [comment]
Verified.
The link is working now and everything else was fixed.
