### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/info_grid#64]
The following weblets solutions were not included in the docs:

- Algorand
- Mastodon
- QVM
- Subsquid
- Caprover worker
- Full VM

**Comment by mohamedamer453** [comment]
Verified from www2.manual.grid.tf

All of the missing solution docs were added.

- [Algorand](https://www2.manual.grid.tf/weblets/weblets_algorand.html)
- [Mastodon](https://www2.manual.grid.tf/weblets/weblets_mastodon.html)
- [Subsquid](https://www2.manual.grid.tf/weblets/weblets_subsquid.html#subsquid)
- [Caprover worker](https://www2.manual.grid.tf/weblets/weblets_caprover_worker.html)
- [Full VM](https://www2.manual.grid.tf/weblets/weblets_fullVm.html#full-virtual-machine)
- QVM: according to #65 it was added but not added to the summary since it's currently hidden
